# This workflow runs C++ unit tests using a Makefile on every push and pull request.

name: C++ Tests

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build_and_test:
    # Use the latest Ubuntu environment, which is well-suited for C++ development.
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository's code.
      # This is a standard action that makes your repository's content
      # available to the workflow.
      - name: Checkout code
        uses: actions/checkout@v4
          
      # Step 2: Create the build artifact directory
      - name: Create build directory
        run: mkdir build

      # Step 3: Setup CMake Environment
      - name: Initialize CMake
        run: cmake -S . -B build
          
      # Step 4: Build the smoke test (test_vector) using CMake.
      - name: Build test_vector
        run: cmake --build build --target test_vector

      # Step 5: Run the test executable.
      - name: Run tests
        run: ./build/test_vector